version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_shorten
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: [ "mongod", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express_shorten
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: env/Dockerfile
    container_name: app_shorten
    ports:
      - "8080:80"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/challenge_short_url
volumes:
  mongo-data:

networks:
  app-network: